name: connectwithme
description: Links to all of my socials

publish_to: "none"

# First Release, sequencially increase like 0.0.2 ...
version: 0.0.1 

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/.

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
